# -*- encoding: utf-8 -*-

=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "BmltClient/version"

Gem::Specification.new do |s|
  s.name        = "BmltClient"
  s.version     = BmltClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["bmlt-enabled"]
  s.email       = ["admin@bmlt.app"]
  s.homepage    = "https://bmlt.app"
  s.summary     = "BMLT Ruby Gem"
  s.description = "BMLT Admin API Client"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
