=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BmltClient::MeetingChangeResource
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BmltClient::MeetingChangeResource do
  let(:instance) { BmltClient::MeetingChangeResource.new }

  describe 'test an instance of MeetingChangeResource' do
    it 'should create an instance of MeetingChangeResource' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BmltClient::MeetingChangeResource)
    end
  end

  describe 'test attribute "date_string"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "service_body_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
