=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BmltClient::RootServerBaseStatisticsServiceBodies
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BmltClient::RootServerBaseStatisticsServiceBodies do
  let(:instance) { BmltClient::RootServerBaseStatisticsServiceBodies.new }

  describe 'test an instance of RootServerBaseStatisticsServiceBodies' do
    it 'should create an instance of RootServerBaseStatisticsServiceBodies' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(BmltClient::RootServerBaseStatisticsServiceBodies)
    end
  end

  describe 'test attribute "num_zones"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "num_regions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "num_areas"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "num_groups"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
