=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BmltClient::RootServerBaseStatistics
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BmltClient::RootServerBaseStatistics do
  let(:instance) { BmltClient::RootServerBaseStatistics.new }

  describe 'test an instance of RootServerBaseStatistics' do
    it 'should create an instance of RootServerBaseStatistics' do
      expect(instance).to be_instance_of(BmltClient::RootServerBaseStatistics)
    end
  end
  describe 'test attribute "service_bodies"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "meetings"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
