=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BmltClient::ValidationError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe BmltClient::ValidationError do
  let(:instance) { BmltClient::ValidationError.new }

  describe 'test an instance of ValidationError' do
    it 'should create an instance of ValidationError' do
      expect(instance).to be_instance_of(BmltClient::ValidationError)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
