=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

# Common files
require 'BmltClient/api_client'
require 'BmltClient/api_error'
require 'BmltClient/api_model_base'
require 'BmltClient/version'
require 'BmltClient/configuration'

# Models
require 'BmltClient/models/authentication_error'
require 'BmltClient/models/authorization_error'
require 'BmltClient/models/conflict_error'
require 'BmltClient/models/error_test'
require 'BmltClient/models/format'
require 'BmltClient/models/format_base'
require 'BmltClient/models/format_create'
require 'BmltClient/models/format_partial_update'
require 'BmltClient/models/format_translation'
require 'BmltClient/models/format_update'
require 'BmltClient/models/meeting'
require 'BmltClient/models/meeting_base'
require 'BmltClient/models/meeting_change_resource'
require 'BmltClient/models/meeting_create'
require 'BmltClient/models/meeting_partial_update'
require 'BmltClient/models/meeting_update'
require 'BmltClient/models/not_found_error'
require 'BmltClient/models/root_server'
require 'BmltClient/models/root_server_base'
require 'BmltClient/models/root_server_base_statistics'
require 'BmltClient/models/root_server_base_statistics_meetings'
require 'BmltClient/models/root_server_base_statistics_service_bodies'
require 'BmltClient/models/server_error'
require 'BmltClient/models/service_body'
require 'BmltClient/models/service_body_base'
require 'BmltClient/models/service_body_create'
require 'BmltClient/models/service_body_partial_update'
require 'BmltClient/models/service_body_update'
require 'BmltClient/models/settings_base'
require 'BmltClient/models/settings_object'
require 'BmltClient/models/settings_update'
require 'BmltClient/models/token'
require 'BmltClient/models/token_credentials'
require 'BmltClient/models/user'
require 'BmltClient/models/user_base'
require 'BmltClient/models/user_create'
require 'BmltClient/models/user_partial_update'
require 'BmltClient/models/user_update'
require 'BmltClient/models/validation_error'

# APIs
require 'BmltClient/api/root_server_api'

module BmltClient
  class << self
    # Customize default settings for the SDK using block.
    #   BmltClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
