=begin
#BMLT

#BMLT Admin API Documentation

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module BmltClient
  class SettingsBase < ApiModelBase
    attr_accessor :google_api_key

    attr_accessor :change_depth_for_meetings

    attr_accessor :default_sort_key

    attr_accessor :language

    attr_accessor :default_duration_time

    attr_accessor :region_bias

    attr_accessor :distance_units

    attr_accessor :meeting_states_and_provinces

    attr_accessor :meeting_counties_and_sub_provinces

    attr_accessor :search_spec_map_center_longitude

    attr_accessor :search_spec_map_center_latitude

    attr_accessor :search_spec_map_center_zoom

    attr_accessor :number_of_meetings_for_auto

    attr_accessor :auto_geocoding_enabled

    attr_accessor :county_auto_geocoding_enabled

    attr_accessor :zip_auto_geocoding_enabled

    attr_accessor :default_closed_status

    attr_accessor :enable_language_selector

    attr_accessor :include_service_body_email_in_semantic

    attr_accessor :bmlt_title

    attr_accessor :bmlt_notice

    attr_accessor :format_lang_names

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'google_api_key' => :'googleApiKey',
        :'change_depth_for_meetings' => :'changeDepthForMeetings',
        :'default_sort_key' => :'defaultSortKey',
        :'language' => :'language',
        :'default_duration_time' => :'defaultDurationTime',
        :'region_bias' => :'regionBias',
        :'distance_units' => :'distanceUnits',
        :'meeting_states_and_provinces' => :'meetingStatesAndProvinces',
        :'meeting_counties_and_sub_provinces' => :'meetingCountiesAndSubProvinces',
        :'search_spec_map_center_longitude' => :'searchSpecMapCenterLongitude',
        :'search_spec_map_center_latitude' => :'searchSpecMapCenterLatitude',
        :'search_spec_map_center_zoom' => :'searchSpecMapCenterZoom',
        :'number_of_meetings_for_auto' => :'numberOfMeetingsForAuto',
        :'auto_geocoding_enabled' => :'autoGeocodingEnabled',
        :'county_auto_geocoding_enabled' => :'countyAutoGeocodingEnabled',
        :'zip_auto_geocoding_enabled' => :'zipAutoGeocodingEnabled',
        :'default_closed_status' => :'defaultClosedStatus',
        :'enable_language_selector' => :'enableLanguageSelector',
        :'include_service_body_email_in_semantic' => :'includeServiceBodyEmailInSemantic',
        :'bmlt_title' => :'bmltTitle',
        :'bmlt_notice' => :'bmltNotice',
        :'format_lang_names' => :'formatLangNames'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'google_api_key' => :'String',
        :'change_depth_for_meetings' => :'Integer',
        :'default_sort_key' => :'String',
        :'language' => :'String',
        :'default_duration_time' => :'String',
        :'region_bias' => :'String',
        :'distance_units' => :'String',
        :'meeting_states_and_provinces' => :'Array<String>',
        :'meeting_counties_and_sub_provinces' => :'Array<String>',
        :'search_spec_map_center_longitude' => :'Float',
        :'search_spec_map_center_latitude' => :'Float',
        :'search_spec_map_center_zoom' => :'Integer',
        :'number_of_meetings_for_auto' => :'Integer',
        :'auto_geocoding_enabled' => :'Boolean',
        :'county_auto_geocoding_enabled' => :'Boolean',
        :'zip_auto_geocoding_enabled' => :'Boolean',
        :'default_closed_status' => :'Boolean',
        :'enable_language_selector' => :'Boolean',
        :'include_service_body_email_in_semantic' => :'Boolean',
        :'bmlt_title' => :'String',
        :'bmlt_notice' => :'String',
        :'format_lang_names' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'default_sort_key',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BmltClient::SettingsBase` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BmltClient::SettingsBase`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'google_api_key')
        self.google_api_key = attributes[:'google_api_key']
      end

      if attributes.key?(:'change_depth_for_meetings')
        self.change_depth_for_meetings = attributes[:'change_depth_for_meetings']
      end

      if attributes.key?(:'default_sort_key')
        self.default_sort_key = attributes[:'default_sort_key']
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      end

      if attributes.key?(:'default_duration_time')
        self.default_duration_time = attributes[:'default_duration_time']
      end

      if attributes.key?(:'region_bias')
        self.region_bias = attributes[:'region_bias']
      end

      if attributes.key?(:'distance_units')
        self.distance_units = attributes[:'distance_units']
      end

      if attributes.key?(:'meeting_states_and_provinces')
        if (value = attributes[:'meeting_states_and_provinces']).is_a?(Array)
          self.meeting_states_and_provinces = value
        end
      end

      if attributes.key?(:'meeting_counties_and_sub_provinces')
        if (value = attributes[:'meeting_counties_and_sub_provinces']).is_a?(Array)
          self.meeting_counties_and_sub_provinces = value
        end
      end

      if attributes.key?(:'search_spec_map_center_longitude')
        self.search_spec_map_center_longitude = attributes[:'search_spec_map_center_longitude']
      end

      if attributes.key?(:'search_spec_map_center_latitude')
        self.search_spec_map_center_latitude = attributes[:'search_spec_map_center_latitude']
      end

      if attributes.key?(:'search_spec_map_center_zoom')
        self.search_spec_map_center_zoom = attributes[:'search_spec_map_center_zoom']
      end

      if attributes.key?(:'number_of_meetings_for_auto')
        self.number_of_meetings_for_auto = attributes[:'number_of_meetings_for_auto']
      end

      if attributes.key?(:'auto_geocoding_enabled')
        self.auto_geocoding_enabled = attributes[:'auto_geocoding_enabled']
      end

      if attributes.key?(:'county_auto_geocoding_enabled')
        self.county_auto_geocoding_enabled = attributes[:'county_auto_geocoding_enabled']
      end

      if attributes.key?(:'zip_auto_geocoding_enabled')
        self.zip_auto_geocoding_enabled = attributes[:'zip_auto_geocoding_enabled']
      end

      if attributes.key?(:'default_closed_status')
        self.default_closed_status = attributes[:'default_closed_status']
      end

      if attributes.key?(:'enable_language_selector')
        self.enable_language_selector = attributes[:'enable_language_selector']
      end

      if attributes.key?(:'include_service_body_email_in_semantic')
        self.include_service_body_email_in_semantic = attributes[:'include_service_body_email_in_semantic']
      end

      if attributes.key?(:'bmlt_title')
        self.bmlt_title = attributes[:'bmlt_title']
      end

      if attributes.key?(:'bmlt_notice')
        self.bmlt_notice = attributes[:'bmlt_notice']
      end

      if attributes.key?(:'format_lang_names')
        self.format_lang_names = attributes[:'format_lang_names']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          google_api_key == o.google_api_key &&
          change_depth_for_meetings == o.change_depth_for_meetings &&
          default_sort_key == o.default_sort_key &&
          language == o.language &&
          default_duration_time == o.default_duration_time &&
          region_bias == o.region_bias &&
          distance_units == o.distance_units &&
          meeting_states_and_provinces == o.meeting_states_and_provinces &&
          meeting_counties_and_sub_provinces == o.meeting_counties_and_sub_provinces &&
          search_spec_map_center_longitude == o.search_spec_map_center_longitude &&
          search_spec_map_center_latitude == o.search_spec_map_center_latitude &&
          search_spec_map_center_zoom == o.search_spec_map_center_zoom &&
          number_of_meetings_for_auto == o.number_of_meetings_for_auto &&
          auto_geocoding_enabled == o.auto_geocoding_enabled &&
          county_auto_geocoding_enabled == o.county_auto_geocoding_enabled &&
          zip_auto_geocoding_enabled == o.zip_auto_geocoding_enabled &&
          default_closed_status == o.default_closed_status &&
          enable_language_selector == o.enable_language_selector &&
          include_service_body_email_in_semantic == o.include_service_body_email_in_semantic &&
          bmlt_title == o.bmlt_title &&
          bmlt_notice == o.bmlt_notice &&
          format_lang_names == o.format_lang_names
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [google_api_key, change_depth_for_meetings, default_sort_key, language, default_duration_time, region_bias, distance_units, meeting_states_and_provinces, meeting_counties_and_sub_provinces, search_spec_map_center_longitude, search_spec_map_center_latitude, search_spec_map_center_zoom, number_of_meetings_for_auto, auto_geocoding_enabled, county_auto_geocoding_enabled, zip_auto_geocoding_enabled, default_closed_status, enable_language_selector, include_service_body_email_in_semantic, bmlt_title, bmlt_notice, format_lang_names].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
